---
title: "Exploring nutrition status- data analysis"
author: "Eric Anku"
format: docx
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```


```{r import-libraries}
# Import libraries
pacman::p_load(
        tidyverse, # Data wrangling and plotting
        gtsummary, # Table summaries
        finalfit, # Labeling, glimpse, and modelling
        here, # Directory manager
        rio # Import data set
)
```

```{r import-dataset}
# Import dataset
cwc <- import(here("data", "cwc_zscore.csv"))
```

```{r cwc-two-remove-variables}
# Remove redundant variables
cwc <- cwc%>%
  select(-c(included, name, age_in_days, age_in_months, cmeasure, oedema, clenhei, cbmi, csex, zlen_flag,
            zwei_flag, zbmi_flag, zwfl_flag, zbmi, age, age_group))
```

```{r factor-sex}
# Convert sex values into a factor
cwc <- cwc%>%
  mutate(
    sex = factor(sex)%>%
      fct_recode(
        "Male" = "1",
        "Female" = "2"
      )
  )
```

```{r relocate-age-to-front}
# Move age data to the front
cwc <- cwc%>%
  relocate(age_months)
```


```{r malnutrition-category}
# Categorise malnutrition status
cwc <- cwc%>%
  mutate (
    stunting = case_when(
      zlen < - 2 & zlen >= -6 ~ "Stunting",
      zlen >= -2 & zlen <= 6 ~ "Normal",
      TRUE ~ "Flag"
    ),
    wasting = case_when(
      zwfl < - 2 & zwfl >= -5 ~ "Wasting",
      zwfl >= -2 & zwfl <= 5 ~ "Normal",
      TRUE ~ "Flag"
    ),
    underweight = case_when(
      zwei < -2 & zwei >= -6 ~ "Underweight",
      zwei >= -2 & zwei <= 5 ~ "Normal",
      TRUE ~ "Flag"
    )
  )
```


```{r labelling-cwc}
# Label variables
cwc <- cwc%>%
  mutate(
    sex = ff_label(sex, "Sex"),
    age_months = ff_label(age_months, "Age (months)"),
    weight = ff_label(weight, "Weight (kg)"),
    lenhei = ff_label(lenhei, "Length/Height (cm)"),
    bwt = ff_label(bwt, "Birth weight (kg)"),
    stunting = ff_label(stunting, "Stunting"),
    wasting = ff_label(wasting, "Wasting"),
    underweight = ff_label(underweight, "Underweight")
  )
```


## Tables


```{r table-one}
# Participant characteristics
cwc%>%
  select(-c(stunting, wasting, underweight))%>%
        tbl_summary(missing_text = "Missing data",
                    statistic = list(c(weight, lenhei, bwt, zwei, zlen, zwfl) ~ "{mean} ({sd})"))%>%add_ci()%>%bold_labels()
```

```{r prevalence-tables-table-one}
# Stunting
cwc%>%
  filter(stunting != "Flag")%>%
  select(stunting)%>%
        tbl_summary(missing_text = "Missing data")%>%add_ci()%>%bold_labels()

# Wasting
cwc%>%
  filter(wasting != "Flag")%>%
  select(wasting)%>%
        tbl_summary(missing_text = "Missing data")%>%add_ci()%>%bold_labels()

#Underweight
cwc%>%
  filter(underweight != "Flag")%>%
  select(underweight)%>%
        tbl_summary(missing_text = "Missing data")%>%add_ci()%>%bold_labels()
```


```{r table_two}
cwc%>%
        tbl_summary(by = sex,
                    missing_text = "Missing data",
                     statistic = list(c(weight, lenhei, bwt, zwei, zlen, zwfl) ~ "{mean} ({sd})")
                    )%>%
        add_p(list(c(weight, lenhei, bwt, zwei, zlen, zwfl) ~ "t.test"))%>%
        bold_p()%>%
        bold_labels()%>%
  add_overall()
```


```{r prevalence-tables-table-two}
# Stunting
cwc%>%
  filter(stunting != "Flag")%>%
  select(stunting, sex)%>%
        tbl_summary(
          by = sex, missing_text = "Missing data")%>%add_ci()%>%bold_labels()

# Wasting
cwc%>%
  filter(wasting != "Flag")%>%
  select(wasting, sex)%>%
        tbl_summary(by = sex,
                    missing_text = "Missing data")%>%add_ci()%>%bold_labels()

#Underweight
cwc%>%
  filter(underweight != "Flag")%>%
  select(underweight, sex)%>%
        tbl_summary(by=sex,
                    missing_text = "Missing data")%>%add_ci()%>%bold_labels()
```



